core/urls.py
from django.urls import path

from core import views

urlpatterns = [

    # Cadastra Usuarios
    path('sis/user/listar', views.listar_usuario, name='lista_usu'),
    path('sis/user/cadastrar/', views.cadastro_usuario, name='cadastrar_usu'),
    path('sis/user/edit/<int:pk>/', views.atualiza_usuario, name='editar_usu'),
    path('sis/user/delete/<int:pk>/', views.delet_usuario, name='delete_usu'),
    path('sis/user/ver/<int:pk>/', views.ver_usuario, name='ver_usuario'),
    path('sis/user/edit/password/', views.edit_password, name='editar_senha'),

    # Cadastra Grupos
    path('sis/grupo/listar', views.lista_grupos, name='lista_grupo'),
    path('sis/grupo/cadastrar/', views.cadastro_grupo, name='cadastrar_grupo'),
    path('sis/grupo/edit/<int:pk>/', views.atualiza_grupo, name='editar_grupo'),
    path('sis/grupo/delete/<int:pk>/', views.delet_grupo, name='deletar_grupo'),

    # login
    path('sis/accounts/login/', views.usu_login, name='login_uso'),
    path('logout/', views.usu_logout, name='usu_logout'),


]

post/urls.py
from django.urls import path

from post import views

urlpatterns = [

    # Dashboard do Sistema
    path('sis/', views.home, name='index'),

    # Posts
    path('sis/post/', views.listar_post, name='posts'),
    path('sis/post/cadastrar/', views.cadastrar_post, name='cadastra_post'),
    path('sis/post/edit/<int:pk>/', views.atualiza_post, name='editar_post'),

    # Categorias
    path('sis/categorias/', views.listar_categoria, name='category'),
    path('sis/categorias/cadastrar/', views.cadastrar_categoria, name='cadastra_category'),
    path('sis/post/edit/<int:pk>/', views.atualiza_post, name='editar_post'),

]

post/models.py
from django.contrib.auth.models import User
from django.db import models
from tinymce.models import HTMLField



class Categoria(models.Model):
    nome = models.CharField(u'Categoria:', max_length=100, unique=True, blank=False)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    date_updated = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        permissions = (
            ('usuario_categoria_add', 'Pode Adicionar Categoria'),
            ('usuario_categoria_edit', 'Pode Editar Categoria'),
        )
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

    def __str__(self):
        return self.nome


class Post(models.Model):
    STATUS_CHOICES = (
        ('1', 'ONLINE'),
        ('2', 'RASCUNHO'),
    )
    titulo = models.CharField(u'Titulo:', max_length=150, blank=False)
    slug = models.SlugField(u'Slug:', max_length=255, unique=True)
    resumo = models.CharField(u'Resumo:', max_length=255, blank=True, null=True)
    content = HTMLField(u'Conteudo:', blank=True, null=True)
    autor = models.ForeignKey(User, on_delete=models.PROTECT, blank=True,  null=True, verbose_name='Autor:')
    categoria = models.ManyToManyField(Categoria, blank=True, verbose_name='Categoria:')
    status = models.CharField(u'Status:', max_length=1, choices=STATUS_CHOICES, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    date_updated = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        permissions = (
            ('usuario_post_add', 'Pode Adicionar Post'),
            ('usuario_post_edit', 'Pode Editar Post'),
        )
        ordering = ['date_created']
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.titulo

post/forms.py
from django.forms import forms, TextInput, Select, SelectMultiple, RadioSelect
from django import forms
#from tinymce_4.fields import TinyMCEFormField

from post.models import Post, Categoria


class RegisterPostForm(forms.ModelForm):
   # content = forms.CharField(widget=TinyMCEFormField(attrs={'cols': 80, 'rows': 30}))

    class Meta:
        model = Post
        fields = ['titulo', 'slug', 'resumo', 'content', 'autor', 'categoria', 'status']

        widgets = {
            'titulo': TextInput(attrs={'class': u'form-control'}),
            'slug': TextInput(attrs={'class': u'form-control'}),
            'resumo': TextInput(attrs={'class': u'form-control'}),
            'autor': Select(attrs={'class': u'form-control'}),
            'categoria': SelectMultiple(attrs={'class': u'form-control'}),
            'status': Select(attrs={'class': u'form-control'}),
        }


class EditaPostForm(forms.ModelForm):
   # content = forms.CharField(widget=TinyMCEFormField(attrs={'cols': 80, 'rows': 30}))

    class Meta:
        model = Post
        fields = ['titulo', 'slug', 'resumo', 'content', 'autor', 'categoria', 'status']

        widgets = {
            'titulo': TextInput(attrs={'class': u'form-control'}),
            'slug': TextInput(attrs={'class': u'form-control'}),
            'resumo': TextInput(attrs={'class': u'form-control'}),
            'autor': Select(attrs={'class': u'form-control'}),
            'categoria': SelectMultiple(attrs={'class': u'form-control'}),
            'status': Select(attrs={'class': u'form-control'}),
        }


class RegisterCategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nome']

        widgets = {
            'nome': TextInput(attrs={'class': u'form-control'}),
        }

post/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse

from post.forms import RegisterPostForm, EditaPostForm, RegisterCategoriaForm
from post.models import Post, Categoria


@login_required
def home(request):
    template = 'dashboard/content.html'
    usuario = User.objects.all().count()
    post = Post.objects.all()
    total_post_offline = post.filter(status=2).count()
    total_post_online = post.filter(status=1).count()
    categorias = Categoria.objects.all().count()
    context = {
        'usuario': usuario,
        'offline': total_post_offline,
        'online': total_post_online,
        'categorias': categorias,
    }

    return render(request, template, context)


@login_required
def listar_post(request):
    """ Lista Posts """
    template = 'posts/posts.html'

    if 'q' in request.GET != False:
        # SE for buscar
        if request.user.is_staff:
            """Busca padão User is_staff"""
            post_busca = Post.objects.all().order_by('-id')

            busca = request.GET.get("q")
            post_list = post_busca.filter(
                Q(titulo__icontains=busca)|
                Q(autor__username=busca)|
                Q(categoria__nome=busca)
            )

        else:
            """Busca tipo User normal"""
            post_busca = Post.objects.filter(autor=request.user.id).order_by('-id')

            busca = request.GET.get("q")
            post_list = post_busca.filter(
                Q(titulo__icontains=busca) |
                Q(categoria__nome=busca)
            )

        total_post = post_list.count()
        total_post_online = post_list.filter(status=1).count()

        page = request.GET.get('page', 1)
        paginator = Paginator(post_list, 2)
        try:
            post = paginator.page(page)
        except PageNotAnInteger:
            post = paginator.page(1)
        except EmptyPage:
            post = paginator.page(paginator.num_pages)

        context = {
            'total': total_post,
            'online': total_post_online,
            'post': post,
        }
        return render(request, template, context)

    else:

        if request.user.is_staff:
            post_list = Post.objects.all().order_by('-id')
        else:
            post_list = Post.objects.filter(autor=request.user.id).order_by('-id')

        total_post = post_list.count()
        total_post_online = post_list.filter(status=1).count()

        page = request.GET.get('page', 1)
        paginator = Paginator(post_list, 2)
        try:
            post = paginator.page(page)
        except PageNotAnInteger:
            post = paginator.page(1)
        except EmptyPage:
            post = paginator.page(paginator.num_pages)

        context = {
            'total': total_post,
            'online': total_post_online,
            'post': post,
        }
        return render(request, template, context)


@login_required
@permission_required('post.usuario_post_add', raise_exception=True)
def cadastrar_post(request):
    """ Cadastra o Post"""
    template_name = 'posts/post_form.html'
    nome_temp = 'Cadastrar'
    if request.method == 'POST':
        form = RegisterPostForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Post Cadastrado com Sucesso!')
            return HttpResponseRedirect(reverse('posts'))
    else:
        form = RegisterPostForm()
    context = {
        'titulo_pagina': nome_temp,
        'form': form,
    }
    return render(request, template_name, context)


@login_required
@permission_required('post.usuario_post_edit', raise_exception=True)
def atualiza_post(request, pk):
    """ Edida o Post"""
    template_name = 'posts/post_form.html'
    nome_temp = 'Atualizar'
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = EditaPostForm(request.POST or None, instance=post)
        if form.is_valid():
            form.save()
            post_titulo = form.cleaned_data.get('titulo')
            messages.success(request, 'O Post <strong> {} </strong> foi atualizado com Sucesso!'.format(post_titulo))
            return HttpResponseRedirect(reverse('posts'))

    else:
        form = EditaPostForm(instance=post)
    context = {
        'titulo_pagina2': nome_temp,
        'form': form,
    }
    return render(request, template_name, context)


@login_required
@permission_required('post.usuario_categoria_edit')
def listar_categoria(request):
    """ Lista Posts """
    template = 'category/categorias.html'
    categoria = Categoria.objects.all()
    total_categoria = categoria.count()

    context = {
        'total': total_categoria,
        'category': categoria,
    }
    return render(request, template, context)


@login_required
@permission_required('post.usuario_categoria_add', raise_exception=True)
def cadastrar_categoria(request):
    """ Cadastra Categoria"""
    template_name = 'category/cadastrar_categoria.html'
    if request.method == 'POST':
        form = RegisterCategoriaForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Categoria Cadastrada com Sucesso!')
            return HttpResponseRedirect(reverse('category'))
    else:
        form = RegisterCategoriaForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)

templates/posts/post_form.html
{% extends 'dashboard/index.html' %}
{% block title %}Cadastro dePost{% endblock %}
{% load crispy_forms_tags %}
{% block body %}

    <div class="container-fluid">
        <!-- Page Heading -->
        {% if titulo_pagina %}
            <h1 class="h3 mb-2 text-gray-800">{{ titulo_pagina }}</h1>
            <p class="mb-4">Adicionar um novo Post. </p>
        {% else %}
            <h1 class="h3 mb-2 text-gray-800">{{ titulo_pagina2 }}</h1>
            <p class="mb-4">Editar o Post. </p>
        {% endif %}

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Preencha o formulário</h6>
            </div>
            <div class="row">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert {{ message.tags }} alert-dismissible text-center" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}
                                {{ message.tags|title }}{% endif %}!</strong> {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="form-group col-sm-8 col-md-7">
                            {{ form.titulo|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-9 col-md-8">
                            {{ form.slug|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-10 col-md-9">
                            {{ form.resumo|as_crispy_field }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-12 col-md-11">
                            <label for="id_message" class="control-label">Conteudo:</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-12 col-md-11">
                            {{ form.content|safe }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="form-group col-sm-7 col-md-6">
                            {{ form.autor|as_crispy_field }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="form-group col-sm-7 col-md-6">
                            {{ form.categoria|as_crispy_field }}
                        </div>
                        <div class="form-group col-sm-7 col-md-6">
                            {{ form.status|as_crispy_field }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-5">
                            <button type="submit" class="btn btn-success small">SALVAR</button>
                        </div>
                        <div class="col-md-5">
                            <a class="btn btn-warning" href="{% url 'posts' %}">CANCELAR</a>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->

    </div>
    <!-- /.col-lg-12 -->
    </div>
    <!-- ----------------------------------------------- -->

{% endblock body %}

{% block scripts %}

    <script>
        $("#id_content").addClass("form-control");
        $('#id_slug').slugify('#id_titulo');

    </script>
{% endblock scripts %}

templates/posts/posts.html
{% extends 'dashboard/index.html' %}
{% block title %}Início{% endblock %}
{% block body %}
    <div class="container-fluid">
        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Posts</h1>
        <p class="mb-4"> Cadastro e Administração de Posts.</p>
        <div class="container box-busca">
            <div class="row">
                <div class="col-md-3 mr-auto mt-2 mt-lg-0">
                    <a href="{% url 'cadastra_post' %}" class="btn btn-primary btn-sm text-margin-bottom"><i
                            class="fas fa-plus"></i> Novo Post</a>
                </div>

                <div class="col-md-6">
                        <form method="get" class="my-2 my-lg-0">
                            <div class="input-group custom-search-form ">
                                <input class="form-control" placeholder="Buscar Post" type="text" name="q"
                                       value="{{ request.GET.q }}">
                                <span class="input-group-btn">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                        </form>

                </div>
            </div>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary"><span
                        class="badge badge-primary">Total: {{ total }}</span> | <span class="badge badge-success">Online: {{ online }}</span>
                </h6>
            </div>
            <div class="card-body">

                <div class="table-responsive">
                    <div class="container box-list">
                        <div class="row">
                            <div class="col-lg-12">
                                {% if messages %}
                                    {% for message in messages %}
                                        <div class="alert {{ message.tags }} alert-dismissible fade show text-center"
                                             role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            {{ message | safe }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>

                        <table class="table table-sm table-hover">
                            <thead>
                            <tr>
                                <th>Titulo</th>
                                <th>Author</th>
                                <th>Categoria</th>
                                <th>Status</th>
                                <th>Opções</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for content_post in post %}
                                <tr>
                                    <td>{{ content_post.titulo|truncatewords:8 }}</td>
                                    <td>{{ content_post.autor }}</td>
                                    <td>
                                        {% for category in content_post.categoria.all %}
                                            {{ category.nome }}
                                        {% endfor %}
                                    </td>
                                    <td>
                                        {% if content_post.status == '1' %}
                                            <span class="badge badge-success">Online</span>
                                        {% else %}
                                            <span class="badge badge-danger">Rascunho</span>
                                        {% endif %}

                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a href="#"
                                               data-confirm='Tem certeza que deseja excluir o Usuário selecionado?'
                                               class="btn btn-primary btn-sm"><i class="far fa-trash-alt"></i></a>
                                            <a href="{% url 'editar_post' content_post.id %}"
                                               class="btn btn-primary btn-sm"><i class="far fa-edit"></i></a>
                                        </div>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="5">
                                         <div class="alert alert-warning alert-dismissible fade show">
                                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                                            <strong>Aviso!</strong> O termo solicitado nao foi encontrado.
                                         </div>

                                    </td>
                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="container">
                            <div class="row">
                                {% if post.has_other_pages %}
                                    <ul class="pagination pagination-sm">
                                        {% if post.has_previous %}
                                            <li class="page-item"><a href="?page={{ post.previous_page_number }}"
                                                                     class="page-link">Anterior</a></li>
                                        {% else %}
                                            <li class="page-item disabled"><a class="page-link" href="#">Anterior</a>
                                            </li>
                                        {% endif %}
                                        {% for i in post.paginator.page_range %}
                                            {% if post.number == i %}
                                                <li class="page-item active"><a class="page-link" href="#">{{ i }}</a>
                                                </li>
                                            {% else %}
                                                <li class="page-item"><a href="?page={{ i }}"
                                                                         class="page-link">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if post.has_next %}
                                            <li class="page-item"><a href="?page={{ post.next_page_number }}"
                                                                     class="page-link">Próximo</a></li>
                                        {% else %}
                                            <li class="page-item disabled"><a class="page-link" href="#">Próximo</a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <!-- Modal -->
                    <div id="modal-usuario-ver" class="modal fade" tabindex="-1" role="dialog"
                         aria-labelledby="myModalLabel"
                         data-backdrop="static">
                        <div class="modal-dialog modal-lg">
                            <!-- Modal content-->
                            <div class="modal-content">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}
{% block scripts %}
    <script>
        $(function () {
            // VER AGENTE
            $(".ver-usuario").click(function () {

                var btn = $(this);
                var htmlToPrint = '' +
                    '<div class="modal-body">' +
                    '<div class="container">' +
                    '<div class="spinner-border" role="status">' +
                    ' <span class="sr-only">Loading...</span>' +
                    '</div>' +
                    '</div>' +
                    '</div>';

                $.ajax({
                    url: btn.attr("data-url"),
                    type: 'get',
                    dataType: 'json',
                    beforeSend: function () {
                        $("#modal-usuario-ver").modal("show");
                        $("#modal-usuario-ver .modal-content").html(htmlToPrint);
                    },
                    success: function (data) {
                        $("#modal-usuario-ver .modal-content").html(data.html_usuario)
                    }
                });
            });

            $('a[data-confirm]').click(function (ev) {
                var href = $(this).attr('href');
                if (!$('#confirm-delete').length) {
                    $('body').append('<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header bg-danger text-white"><h5 class="modal-title" id="exampleModalLabel">Excluir Item</h5><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button></div><div class="modal-body">Tem certeza que deseja excluir o item selecionado?</div><div class="modal-footer"><button type="button" class="btn btn-success" data-dismiss="modal">Cancelar</button><a class="btn btn-danger text-white" id="dataComfirmok" >Apagar</a></div></div></div></div>');
                }
                $('#dataComfirmok').attr('href', href);
                $('#confirm-delete').modal({shown: true});
                return false;
            });

        });


    </script>
{% endblock scripts %}